# PostgreSQL. Versions 8.2 and up are supported.

#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: diaspora_development


test:
  <<: *default
  database: diaspora_test



#
production:
  <<: *default
  database: diaspora_production

  username: opu
  password: <%= ENV['MINE_DATABASE_PASSWORD'] %>
