# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d9644a749bd64dfa2764b1e9435b27494f14db3fe168e967d64d16f181d63a35b0e80a259984898d18a8cf659a27eb13f01d97ac2fa29fa1ad32cc167020638

test:
  secret_key_base: 6092cdae366046f5d469a226942d3f6ccdef5a25abaaaa2612cedc8687bd8a1a2992df0e898b2e090f011752cd15e847f4f1f9eb3fb57ea12e44c5e40408d747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
